INSERT INTO `vendors` (`id`, `vendor`, `vperson`, `vaddress`, `vcontact`) VALUES
(3, 'Inv Adj', '', '', ''),
(4, 'Wiscon Enterprises', '', '', ''),
(5, 'Lighten General Merchandise', '', '', ''),
(6, 'St. Charbel Trading', '', '', ''),
(7, 'Zeta Int\'lTrading Corp.', '', '', ''),
(8, 'Legacy Steel Corporation', '', '', ''),
(9, 'ASK Sales', '', '', ''),
(10, 'Janpas Trading & Elec. Supply', '', '', ''),
(11, 'Ono Hardware & Lumber', '', '', ''),
(12, 'CKR Hardware', '', '', ''),
(13, 'Jeron Int\'l Trading Corp.', '', '', ''),
(14, 'Fine Things Corp.', '', '', ''),
(15, 'Paradise Chemical Corporation', '', '', ''),
(16, 'Evan Hardware', '', '', ''),
(17, 'Silver World Enterprises', '', '', ''),
(18, 'Lunar Steel  Corporation', '', '', ''),
(19, 'JTS Po Marketing', '', '', ''),
(20, 'Bionic Builders Center', '', '', ''),
(21, 'Firefly Electric & Lighting', '', '', ''),
(22, 'Star Ace Lumber Corp.', '', '', ''),
(23, 'Great A\'s Marketing Corp.', '', '', ''),
(24, 'Han\'s Infinite Tools', '', '', ''),
(25, 'New Top Steel Builders Center', '', '', ''),
(26, 'Hundred Island Chemical Corp.', '', '', ''),
(27, 'Naprex Commercial Corp.', '', '', ''),
(28, 'Parklane Commercial Corp.', '', '', ''),
(29, 'YIC Southern Electrical', '', '', ''),
(30, 'Koten Enterprises Co.', '', '', ''),
(31, 'Advance Industrial Tools', '', '', ''),
(32, 'L.A Plywood Sales Corp.', '', '', ''),
(33, 'Antar Trading Company', '', '', ''),
(34, 'Win Marketing', '', '', ''),
(35, 'Philips Wire & Cable Co.', '', '', ''),
(36, 'Filway Consumer Sales', '', '', ''),
(37, 'Wistom Construction Supply Inc', '', '', ''),
(38, 'Kim Liang Construction Supply', '', '', ''),
(39, 'Sinewell Marketing Corp.', '', '', ''),
(40, 'Joson Plastic Products', '', '', ''),
(41, 'YH Marketing', '', '', ''),
(42, 'Melbourne Industrial Sales', '', '', ''),
(43, 'Prestigious Hardware', '', '', ''),
(44, 'LS International Marketing', '', '', ''),
(45, 'Wilcon Builder\'s Supply Inc.', '', '', ''),
(46, 'Jolesco Enterprises', '', '', ''),
(47, 'Paco Asia Plumbing & Hardware', '', '', ''),
(48, 'Poweree Commercial Corp.', '', '', ''),
(49, 'Sea King Enterprises Co. Ltd.', '', '', ''),
(50, 'Powerluck Marketing', '', '', ''),
(51, 'Jobbert  Marketing', '', '', ''),
(52, 'Do-All Marketing Co.', '', '', ''),
(53, 'Granitex Marketing', '', '', ''),
(54, 'SNS Wholesale Trading Corp.', '', '', ''),
(55, 'Sulit Marketing', '', '', ''),
(56, 'MIG System', '', '', ''),
(57, 'First Player Trading', '', '', ''),
(58, 'Powerry Int\'l Traders', '', '', ''),
(59, 'Uni-Built Trading Center', '', '', ''),
(60, 'Gerwin Trading', '', '', ''),
(61, 'Lockwood Enterprises', '', '', ''),
(62, 'Sacaris Trading Co.', '', '', ''),
(63, 'High Trend', '', '', ''),
(64, 'Powerteam Commercial Inc.', '', '', ''),
(65, 'TCM Marketing', '', '', ''),
(66, 'Best Well Enterprises Corp.', '', '', ''),
(67, 'Martian Steel Corp.', '', '', ''),
(68, 'Tri-Gold Builder\'s Centrum', '', '', ''),
(69, 'ABH Marketing', '', '', ''),
(70, 'Her Sun Marketing', '', '', ''),
(71, 'Sonic Steel', '', '', ''),
(72, 'Golden Lion Enterprises', '', '', ''),
(73, 'Golden Hit Corp.', '', '', ''),
(74, 'Joseph  Sy', '', '', ''),
(75, 'Nevada Industrial Sales', '', '', ''),
(76, 'Venus Steel Corp.', '', '', ''),
(77, 'Amon Marketing', '', '', ''),
(78, 'Sterling Steel', '', '', ''),
(79, 'H & K Marketing', '', '', ''),
(80, 'Nation Ceramics Manufacturing', '', '', ''),
(81, 'Vertan', '', '', ''),
(82, 'New Quepe Hardware', '', '', ''),
(83, 'Allied Sales Center', '', '', ''),
(84, 'Thames Enterprises Corp.', '', '', ''),
(85, 'New Dayton Hardware', '', '', ''),
(86, 'New Antonio\'s Trading Corp.', '', '', ''),
(87, 'Hafelson Manufacturing Corp.', '', '', ''),
(88, 'Harrows Industrial Sales', '', '', ''),
(89, 'Nissan Commercial', '', '', ''),
(90, 'RnR Steel', '', '', ''),
(91, 'Kenji Marketing (DO NOT USE)', '', '', ''),
(92, 'Ever World Merchandising', '', '', ''),
(93, 'E.V.Y.  Const & Development', '', '', ''),
(94, 'Kengi Marketing', '', '', ''),
(95, 'Mar-Win Hardware & Const.', '', '', ''),
(96, '3 Gold Marketing Corp.', '', '', ''),
(97, 'Danghem Commercial', '', '', ''),
(98, 'Asia Luck Marketing', '', '', ''),
(99, 'Cord Chemicals', '', '', ''),
(100, 'Danhil Enterprises', '', '', ''),
(101, 'Puyat Steel Corp.', '', '', ''),
(102, 'Do-All Marketing Co. DUPLICATE', '', '', ''),
(103, 'Mrs. Minda Legarda', '', '', ''),
(104, 'Sresla', '', '', ''),
(105, 'Cash', '', '', ''),
(106, 'BPI', '', '', ''),
(107, 'BPI', '', '', ''),
(108, 'Sialay Shell Station', '', '', ''),
(109, 'Steel Circle Distributors', '', '', ''),
(110, 'Eastern Wire Manufacturing Inc', '', '', ''),
(111, 'Pointer Enterprises', '', '', ''),
(112, 'NEBCON', '', '', ''),
(113, 'S.G.U.', '', '', ''),
(114, 'Ortemer', '', '', ''),
(115, 'World Wood', '', '', ''),
(116, 'Solid Base', '', '', ''),
(117, 'Pangulo', '', '', ''),
(118, 'Cocolight', '', '', ''),
(119, 'Pouri Marketing', '', '', ''),
(120, 'Eurolux', '', '', ''),
(121, 'Romy', '', '', ''),
(122, 'Steel Master', '', '', ''),
(123, 'AJO Marketing', '', '', ''),
(124, 'Future Point Marketing', '', '', ''),
(125, 'Master Wealth', '', '', ''),
(126, 'Uy', '', '', ''),
(127, 'All Win', '', '', ''),
(128, 'Philflex', '', '', ''),
(129, 'Durcom', '', '', ''),
(130, 'United Hardware', '', '', ''),
(131, 'RLM Rubber Trading', '', '', ''),
(132, 'Rucky Marketing', '', '', ''),
(133, 'Well Share', '', '', ''),
(134, 'A. Cube', '', '', ''),
(135, 'Chem Trading', '', '', ''),
(136, 'Myco Marketing', '', '', ''),
(137, 'Beacon Express Ent. Inc.', '', '', ''),
(138, 'Kibou Enterprises', '', '', ''),
(139, 'G Chemtrading Corp.', '', '', ''),
(140, 'Jesus', '', '', ''),
(141, 'Fighter Lock', '', '', ''),
(142, 'Matimco', '', '', ''),
(143, 'Leysto Sales Co.', '', '', ''),
(144, 'K & J Metal Trading', '', '', ''),
(145, 'IKHea Lightings Inc.', '', '', ''),
(146, 'Ret. From Customer', '', '', ''),
(147, 'Ret. From Store', '', '', ''),
(148, 'Titanio International Corporat', '', '', ''),
(149, 'L-Jean', '', '', ''),
(150, 'South Alliance', '', '', ''),
(151, 'New Lucky Star', '', '', ''),
(152, 'Home Valley Gen Merch', '', '', ''),
(153, '366 Merchandising', '', '', ''),
(154, 'Golden Alliance International', '', '', ''),
(155, 'Bestank', '', '', ''),
(156, 'ASCD Industrial Sales', '', '', ''),
(157, 'M.Barcelona Paint Center', '', '', ''),
(158, 'Center Sun Merchandizing', '', '', ''),
(159, 'Sysons Steel Center', '', '', ''),
(160, 'Bosny Marketing', '', '', ''),
(161, 'Conwel Trading', '', '', ''),
(162, 'Phil. Hardware', '', '', ''),
(163, 'Solidjade Company', '', '', ''),
(164, 'Shecon Ind & Const. Supply', '', '', ''),
(165, 'Clearstone Enterprises', '', '', ''),
(166, 'Wellhome Ventures', '', '', ''),
(167, 'Sheridan', '', '', ''),
(168, 'The Original American', '', '', ''),
(169, 'Hap Suy Hardware', '', '', ''),
(170, 'Macropoint', '', '', ''),
(171, 'J.M. Aquino', '', '', ''),
(172, 'Manthe Traque?a', '', '', ''),
(173, 'LGK Marketing (Lincoln)', '', '', ''),
(174, 'Ramirez', '', '', ''),
(175, 'Agusan Plywood Corp.', '', '', ''),
(176, 'Allied Star Trading', '', '', ''),
(177, 'Fortune Cement Corporation', '', '', ''),
(178, 'GBC Metal Craft', '', '', ''),
(179, 'Gain More Marketing', '', '', ''),
(180, 'HK Wood Master Marketing', '', '', ''),
(181, 'J.N.T', '', '', ''),
(182, 'JT Ayson Commercial', '', '', ''),
(183, 'KCJT Group', '', '', ''),
(184, 'MGS Builders & Gen. Contractor', '', '', ''),
(185, 'Magna Prime Dist. Corp.', '', '', ''),
(186, 'Nebcon Marketing Corp', '', '', ''),
(187, 'Ourcom Trading Company', '', '', ''),
(188, 'PDE Marketing', '', '', ''),
(189, 'Parfait Directe Energisant', '', '', ''),
(190, 'Philman Commercial', '', '', ''),
(191, 'Prince of Merchant Entr.', '', '', ''),
(192, 'Ricsonwin Marketing Corp.', '', '', ''),
(193, 'SMWPI', '', '', ''),
(194, 'Shurely Win Multi Corp.', '', '', ''),
(195, 'Tasman Industrial Corp', '', '', ''),
(196, 'Tristar Trusted Mktg.', '', '', ''),
(197, 'Truetemper Hardware Corp.', '', '', ''),
(198, 'Uniprime Beaver', '', '', ''),
(199, 'Vicson Industrial Sales', '', '', ''),
(200, 'Vine Marketing', '', '', ''),
(201, 'Waby Enterprises', '', '', ''),
(202, 'Winlyson Inc.', '', '', ''),
(203, 'M. Ayroso Lumber & Hardware', '', '', ''),
(204, 'Hardest Way General Merchandis', '', '', ''),
(205, 'Atlanta Industries Inc.', '', '', ''),
(206, 'Dale Starr Enterprises', '', '', ''),
(207, 'Greencore Enterprise', '', '', ''),
(208, 'Brixton Construction & Indtl', '', '', ''),
(209, 'Bostik', '', '', ''),
(210, '3 E\'s Home Builders', '', '', ''),
(211, 'Anonas Construction', '', '', ''),
(212, 'Power Depot Inc', '', '', ''),
(213, 'Alabang Home Depot', '', '', ''),
(214, 'Green Island Asia Pacific', '', '', ''),
(215, 'Joji Trading', '', '', ''),
(216, 'Giga Trading', '', '', ''),
(217, '1225 Trading', '', '', ''),
(218, 'Luzon Ilumina Corporation', '', '', ''),
(219, 'Delsa Chemicals', '', '', ''),
(220, 'Avesco Marketing Corp', '', '', ''),
(221, 'Jecar Trading', '', '', ''),
(222, 'Standpoint', '', '', ''),
(223, 'M & W', '', '', ''),
(224, 'New San Pablo Trading', '', '', ''),
(225, 'Ralge Steel Trading Inc', '', '', ''),
(226, 'Uni Favorex Trading', '', '', ''),
(227, 'Glober International Distribut', '', '', ''),
(228, '789 Enterprises', '', '', ''),
(229, 'Nucor Steel Bender Corporation', '', '', ''),
(230, 'Lucena Newwood Corporation', '', '', ''),
(231, 'Yatai International Corporatio', '', '', ''),
(232, 'Emerald Vinyl Corporation', '', '', ''),
(233, 'Multiverse Trading', '', '', ''),
(234, 'Motoking Importer', '', '', ''),
(235, 'Laydian Marketing', '', '', ''),
(236, 'Lesvenz Marketing', '', '', ''),
(237, 'Donata-Victoria Marketing', '', '', ''),
(238, 'Davies Paint Philippines Inc', '', '', ''),
(239, 'Star Axis Trading Corp.', '', '', ''),
(240, 'Sealbond Chemical Industries I', '', '', ''),
(241, 'Sheridan Distributor Metro Man', '', '', ''),
(242, 'Fighter Lock Philippines Corp', '', '', ''),
(243, 'Bestank Manufacturing Corp', '', '', ''),
(244, 'Solid Star General Merchandisi', '', '', ''),
(245, 'Gran Lumix Corporation', '', '', ''),
(246, 'Nemar Lumber & Hardware Corpor', '', '', ''),
(247, 'One-Man Merchandising', '', '', ''),
(248, 'One Man Merchandising ', '', '', ''),
(249, 'Uniprime Beaver Steel Products', '', '', ''),
(250, 'Minami Manufacturing Corporati', '', '', ''),
(251, 'BestResource', '', '', ''),
(252, 'Todos Amigos ', '', '', ''),
(255, 'Testing Merchandise', 'Marjay Tapay', '#123 , Shaw Blvd , Mandaluyong City', '09123456789');